spring.profiles.active: local
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test
  application:
    name: main-service
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring.config.activate.on-profile: local
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/playground?serverTimezone=Asia/Seoul&characterEncoding=utf8
---
spring.config.activate.on-profile: develop
server:
  port: 0
spring:
  datasource:
    url: jdbc:mariadb://pg-mariadb:3306/playground?serverTimezone=Asia/Seoul&characterEncoding=utf8