export { default as useUserRegister } from './useUserRegister';
export { default as useLogin } from './useLogin';
export { default as useMainVideoList } from './useMainVideoList';
export { default as useFriendList } from './useFriendList';
export { default as useDeleteFriend } from './useDeleteFriend';
export { default as useGetFriendReqList } from './useGetFriendReqList';
export { default as useHandleFriendReq } from './useHandleFriendReq';
export { default as useGetNotiList } from './useGetNotiList';
export { default as useUploadVideo } from './useUploadVideo';
