version: '3.7'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  chat-service:
    container_name: chat-service
    image: rlagksml99/chat-service
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis
    restart: always
