version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
#    networks:
#      sg-network:
#        ipv4_address: 172.22.0.2
    restart: always

  chat-service:
    container_name: chat-service
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
    links:
      - redis
#    networks:
#      sg-network:
#        ipv4_address: 172.22.0.3

#networks:
#  sg-network:
#    name: sg-network
#    external: true
