server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  profiles:
    include:
      - auth
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:63669"
            allowCredentials: true
            allowedHeaders:
              - x-requested-with
              - content-length
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/refresh
            - Method=POST,GET,DELETE,PUT
          filters:
            - RewritePath=/user-service(?<segment>/?.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/email
            - Method=POST,GET,DELETE,PUT
          filters:
            - RewritePath=/user-service(?<segment>/?.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/password
            - Method=POST,GET,DELETE,PUT
          filters:
            - RewritePath=/user-service(?<segment>/?.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/nickname
            - Method=POST,GET,DELETE,PUT
          filters:
            - RewritePath=/user-service(?<segment>/?.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=POST,GET,DELETE,PUT
          filters:
            - RewritePath=/user-service(?<segment>/?.*), /$\{segment}
            - AuthenticationFilter
        - id: main-service
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/main-service/**
            - Method=POST,GET,DELETE,PUT
          filters:
            - RewritePath=/main-service(?<segment>/?.*), /$\{segment}
            - AuthenticationFilter
        - id: upload-service
          uri: lb://UPLOAD-SERVICE
          predicates:
            - Path=/upload-service/**
            - Method=POST,GET,DELETE,PUT
          filters:
            - RewritePath=/upload-service(?<segment>/?.*), /$\{segment}
            - AuthenticationFilter
        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/room-service/**
            - Method=POST,GET,DELETE,PUT
          filters:
            - RewritePath=/room-service(?<segment>/?.*), /$\{segment}
            - AuthenticationFilter
        - id: video-service
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/video-service/**
            - Method=POST,GET,DELETE,PUT
          filters:
            - RewritePath=/video-service(?<segment>/?.*), /$\{segment}
            - AuthenticationFilter
