spring.profiles.active: local
server:
  port: 8888
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
---
spring.config.activate.on-profile: local
spring:
  redis:
    host: localhost
    port: 6379
---
spring.config.activate.on-profile: develop
spring:
  redis:
    host: redis
    port: 6379