spring.profiles.active: local
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
---
spring.config.activate.on-profile: local
spring:
  redis:
    host: localhost
    port: 6379
