spring.profiles.active: local
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  # freemarker:
  #   cache: false

---
spring.config.activate.on-profile: local
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/playground
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      host: localhost
      port: 27017
      database: playground
  redis:
    host: localhost
    port: 6379

---
spring.config.activate.on-profile: develop
#spring.redis:
#  host:
#  port:

