cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIAXYE4LDC4WFY56FPY
      secret-key: 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
    s3:
      image:
        bucket: sg.playground
        input-dir: video/input
        output-dir: video/output