spring.profiles.active: local
spring:
  profiles:
    include:
      - s3
  application:
    name: upload-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test
  servlet:
    multipart:
      enabled: true
#      file-size-threshold:  #??? ???? ???? ??? (default: 0B)
#      location:               #???? ??? ?? ?? ??
      max-file-size: 5MB
      max-request-size: 5MB
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
---
spring.config.activate.on-profile: local
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/playground?characterEncoding=utf8
---
spring.config.activate.on-profile: develop
server:
  port: 0
spring:
  datasource:
    url: jdbc:mariadb://pg-mariadb:3306/playground?characterEncoding=utf8
