spring.profiles.active: local
spring:
  profiles:
    include:
      - s3
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
---
spring.config.activate.on-profile: local
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/playground?characterEncoding=utf8
service:
  ip:
    chat-service: http://localhost:8888
bin:
  path: C:\Projects\Playground\bin
ffmpeg:
  path: C:\Program Files\ffmpeg-5.0-essentials_build\bin\ffmpeg.exe
ffprobe:
  path: C:\Program Files\ffmpeg-5.0-essentials_build\bin\ffprobe.exe
---
spring.config.activate.on-profile: develop
server:
  port: 0
spring:
  datasource:
    url: jdbc:mariadb://pg-mariadb:3306/playground?characterEncoding=utf8
service:
  ip:
    chat-service: http://chat-service:8888
bin:
  path: /tmp
ffmpeg:
  path: /usr/bin/ffmpeg
ffprobe:
  path: /usr/bin/ffprobe