version: "3"
services:
  chat-service:
    container_name: chat-service
    image: rlagksml99/chat-service:latest
    environment:
      spring.datasource.url: jdbc:mariadb://3.19.12.178:3306/playground
      spring.redis.host: 52.78.108.27
      spring.redis.port: 6379
    ports:
      - "8888:8888"
    restart: always