version: "3"
services:
  pg-mariadb:
    container_name: pg-mariadb
    image: mariadb
    hostname: pg-mariadb
    environment:
      MYSQL_DATABASE: playground
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - "../data/mariadb:/docker-entrypoint-initdb.d/:ro"
    ports:
      - "3306:3306"
    networks:
      - sg-network

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - sg-network

  user-service:
    container_name: user-service
    image: wodndl895/user-service:1.0
    environment:
      spring.datasource.url: jdbc:mariadb://pg-mariadb:3306/playground
      eureka.client.serviceUrl.defaultZone: http://service-discovery:8761/eureka/
    depends_on:
      - pg-mariadb
      - redis
    links:
      - pg-mariadb
      - redis
    restart: always
    networks:
      - sg-network

  chat-service:
    container_name: chat-service
    image: rlagksml99/chat-service:latest
    environment:
      eureka.client.serviceUrl.defaultZone: http://service-discovery:8761/eureka/
    depends_on:
      - redis
    links:
      - redis
    restart: always
    ports:
      - "8888:8888"
    networks:
      - sg-network

  service-discovery:
    container_name: service-discovery
    image: wodndl895/service-discovery:1.0
    ports:
      - "8761:8761"
    networks:
      - sg-network
  apigateway-service:
    image: wodndl895/api-gateway:1.0
    ports:
      - "8000:8000"
    environment:
      eureka.client.serviceUrl.defaultZone: http://service-discovery:8761/eureka/
    depends_on:
      - service-discovery
    networks:
      - sg-network

networks:
  sg-network:
    name: sg-network
    external: true
    driver: bridge