cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-2
    credentials:
      access-key: AKIASLT7FZRZIT3E2A3Y
      secret-key: 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
    s3:
      bucket: sgs-playground