server:
  port: 50002

spring:
  profiles:
    include:
      - s3
  application:
    name: room-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.19.12.178:3306/playground
    username: root
    password: test
