version: "3.9"
services:
  service-discovery:
    container_name: service-discovery
    image: wodndl895/service-discovery:1.0
    ports:
      - 8761:8761
    networks:
      - sg-network

  api-gateway:
    container_name: api-gateway
    image: wodndl895/api-gateway:1.0
    ports:
    - 8000:8000
    environment:
      eureka.client.serviceUrl.defaultZone: http://3.18.120.82:8761/eureka/
    depends_on:
      - service-discovery
    networks:
      - sg-network

networks:
  sg-network:
    name: sg-network
    external: true