spring.profiles.active: local
server:
  port: 9999
spring:
  profiles:
    include:
      - jwt
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test

---
spring.config.activate.on-profile: local
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/playground?characterEncoding=utf8
---
spring.config.activate.on-profile: develop
spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mariadb://pg-mariadb:3306/playground?characterEncoding=utf8